### ISSUE TITLE
Issue at the time of issuing on document store

### ISSUE THREAD

**Issue by vaibhavpawarautomaxis** [TradeTrust/documentation#131]
We got the following error, saying that we do not have enough balance. When we try to do the issuing on document store. We are also attaching our code snippet for your reference see below:

 ```
      //Issuing of documents
        const unconnectedWallet = new Wallet(privateKey);
        const { ethereum } = window as any;
        const provider = new ethers.providers.Web3Provider(ethereum)
        await provider.send("eth_requestAccounts", []);
        const wallet = unconnectedWallet.connect(provider);
            
        const documentStore = DocumentStoreFactory.connect(documentStoreAddress, wallet);
        console.log('document transaction');
        console.log('Document Store:-', documentStore);
        const tx = await documentStore.issue(merkleRoot);
        console.log('iisue transaction');
        const receipt = await tx.wait();
        console.log(`Issue Transaction: ${JSON.stringify(receipt)}`);
        const isIssued = await documentStore.isIssued(merkleRoot);
        console.log(`Has been Issued: ${isIssued}`); 

```

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"code":-32000,"message":"gas required exceeds allowance (0)"},"method":"estimateGas","transaction":{"from":"0x9CA623e97Bd7E155Ab66E8Fc6349057531B9044D","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x053b2bc718"},"to":"0x41379d970D9b1938B2c349058f0BF99d997De45F","data":"0x0f75e81f10302e49fb3ee39d222a53b0d887b882564fd31d3a2135cfd60274fda93fdf9d","type":2,"accessList":null}}, tx={"data":"0x0f75e81f10302e49fb3ee39d222a53b0d887b882564fd31d3a2135cfd60274fda93fdf9d","to":{},"from":"0x9CA623e97Bd7E155Ab66E8Fc6349057531B9044D","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x053b2bc718"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)

![Screenshot 2023-12-26 174553](https://github.com/TradeTrust/documentation/assets/152165841/e8364301-d412-486f-9693-4b0cc1c0b3b2)

**Comment by isaackps** [comment]
Hi,
This error might be due to it cannot find the smart contract on the specific blockchain network therefore it could not estimate the gas fee to use.

Could you go to the previous step to deploy a document store?

I would suggest that you start the tutorial from the start to get a better understanding of how we would prepare and create the document and then issue it.

Hope this helps solve your issue.
