### ISSUE TITLE
config topic getting large

### ISSUE THREAD

**Issue by simboonlong** [TradeTrust/documentation#39]
- config topic is getting bigger in 1 long page -> https://docs.tradetrust.io/docs/document-creator/config-file
- can break them up into nested sections (sub nest the topics within sidebar too)
  - Network field
  - Wallet field
  - Forms field
  - Document Storage field
- writeup short descriptions for each

**Comment by cavacado** [comment]
hmm, actually i would prefer all sections in one document though, but if its necessary yup break it up.

**Comment by simboonlong** [comment]
cmd + f guy 😂
